### ISSUE TITLE
[CHORE] Vite 8 migration (rolldown) — deferred from Dependabot #662

### ISSUE THREAD

**Issue by Sturmi77** [Sturmi77/correlcore#665]
Dependabot proposed Vite 6.4.3 → 8.2.0 (#662). Deferred to a deliberate migration because Vite 8 is a major bump that **skips v7 and switches the bundler to rolldown**, so it needs more than a green CI run.

## Known breaking change (from #662 CI)
`build.rollupOptions.output.manualChunks` object form is rejected by Rolldown (`"manualChunks is not a function"`).
**Preferred fix:** remove `manualChunks` and let Rolldown split (or migrate to Rolldown `codeSplitting.groups`). Function-form `manualChunks` is **deprecated** in Vite 8.

## Explicitly out of scope
- SvelteKit 3 major upgrade (separate issue; Kit 2.53+ already supports Vite 8)
- Node version bump beyond current `.nvmrc` (22) unless forced by a peer later

### Sprint 1 — Baseline + Vite-6-safe config prep — DONE (#825)
- [x] Remove object `manualChunks` on Vite 6
- [x] `pnpm build` + `build:capacitor`; largest client JS ≤ 150 KB gz
- [x] Unit + E2E smoke green

### Sprint 2 — Vite 8 + plugin major — DONE (#826)
- [x] `vite` → `^8` (8.2.2); `@sveltejs/vite-plugin-svelte` already ^7
- [x] Keep Kit 2.x; Vitest 4.x; no SK3; no `legacy.inconsistentCjsInterop`
- [x] Build / typecheck / lint / tests / capacitor build green

### Sprint 3 — Runtime smoke + perf budget — DONE (#833)
- [x] E2E smoke + journeys + GDPR (export/privacy/delete)
- [x] Perf budget held (~40 KB gz largest client chunk)
- [x] Co-occurrence `pairs` guards + journey selector updates

### Sprint 4 — Capacitor / Android closeout
**Goal:** Second build target + store pipeline proof.

**Exit tests**
- [x] `build:capacitor` + `cap sync` succeed on Vite 8 / Rolldown
- [ ] CI `assemble-debug` green on the completing PR (path-filtered Android workflow)
- [x] Synced WebView assets use absolute `/_app/...` (no `../_app` relative breakage)
- [x] Dependabot #662 already closed/superseded
- [ ] Completing PR uses `Closes #665`

**Local note:** full Gradle assemble may require Android SDK; CI covers `assemble-debug`. Capacitor config validate (`pnpm --filter @correlcore/android validate`) is green without SDK.

## Why not merge #662 as-is
A major bundler swap merged straight from a Dependabot PR risks subtle runtime/output differences that CI green alone doesn't catch. Doing it deliberately keeps the bundler change reviewable.
